services:
  eldoria-api:
    container_name: eldoria-api
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - supabase_network

networks:
  supabase_network:
    external: true
    name: supabase_default
